spring:
    redis:
      host: 112.124.26.183
      port: 6379
      jedis:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 500 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
      lettuce:
        shutdown-timeout: 0  # 连接超时时间（毫秒）
    application:
        name: cloud-payment-service
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://112.124.26.183:3306/one?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

server:
  port: 12345

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lzz.springcloud.bean
filepath: file:/D:/peis_public/ok
